### ISSUE TITLE
ERROR: ECONNRESET on `pnpm devnet deploy`

### ISSUE THREAD

**Issue by mradkov** [hackbg/fadroma#192] opened 2023-08-05 18:51 UTC
Unable to deploy contracts to devnet even on a clean state (after deleting `state/` folder).
  
  Here are some logs:
  
  ```log
  LOG  container: fadroma-devnet bind container port 1317/tcp to host port 1317
  LOG  fadroma-devnet @ localhost:1317 created container 2cf1ac86
  LOG  fadroma-devnet @ localhost:1317 starting container 2cf1ac86
  LOG  docker container 2cf1ac86 trailing logs, waiting for: Validating proposal
  LOG  docker container 2cf1ac86 ~/.secretd/config/genesis.json missing -> performing genesis
  LOG  docker container 2cf1ac86 Ensuring a clean slate...
  LOG  docker container 2cf1ac86 Establishing initial config...
  LOG  docker container 2cf1ac86 Adding genesis accounts...
  LOG  docker container 2cf1ac86 Creating genesis transaction...
  LOG  docker container 2cf1ac86 Genesis transaction written to "/root/.secretd/config/gentx/gentx-115aa0a629f5d70dd1d464bc7e42799e00f4edae.json"
  LOG  docker container 2cf1ac86 Bootstrapping chain...
  LOG  docker container 2cf1ac86 Sprinkling holy water...
  LOG  docker container 2cf1ac86 Configuring the node to support lcp (CORS proxy)...
  LOG  docker container 2cf1ac86 Spawning lcp (CORS proxy)...
  LOG  docker container 2cf1ac86 Launching the node...
  LOG  docker container 2cf1ac86 $ source /opt/sgxsdk/environment && RUST_BACKTRACE=1 secretd start --bootstrap --rpc.laddr tcp://0.0.0.0:26657 --grpc.address 0.0.0.0:9090 --grpc-web.address 0.0.0.0:9091
  LOG  docker container 2cf1ac86 Validating proposal  1 with random:  7bd6c5b83e4768a91257cb36078ee6e26a5c3c3fcdb32778d57310e20ee269d23979e70b8d097bedf6cb22545c95eeb6 proof:  2e9ebd7398eb2aada71707db3680693e786c9e81bef0fbdf6f9bbe7e31a8e05d hash:  e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  LOG  docker found expected message: Validating proposal
  LOG  docker throwing 7 seconds away...
DEBUG  @hackbg/port: localhost:1317 Connecting...
 INFO  @hackbg/port: localhost:1317 Connected
  LOG  secret1glew89c3jwk0a5n7kns68ek6lmzcjk6g9dpzmx @ fadroma-devnet authenticated
ERROR  secret1glew89c3jwk0a5n7kns68ek6lmzcjk6g9dpzmx @ fadroma-devnet Upload failed with code ECONNRESET: request to http://localhost:1317/cosmos/auth/v1beta1/accounts/secret1glew89c3jwk0a5n7kns68ek6lmzcjk6g9dpzmx? failed, reason: read ECONNRESET
ERROR  deploy The command "deploy" failed in 13.893s
ERROR  deploy fail                                             13.893s s

 INFO  fadroma-devnet @ localhost:1317 running on port 1317
 INFO  fadroma-devnet @ localhost:1317 from container 2cf1ac86
 INFO  fadroma-devnet @ localhost:1317 manual reset with:
 INFO  fadroma-devnet @ localhost:1317 $ docker kill 2cf1ac86 && docker rm 2cf1ac86 && sudo rm -rf state/fadroma-devnet
file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@fadroma+scrt@10.1.0_@fadroma+agent@1.0.1_secretjs@1.9.3/node_modules/@fadroma/scrt/scrt-chain.ts:322
            throw new Error.Failed.Upload(result);
                  ^

FadromaError_Failed_Upload: request to http://localhost:1317/cosmos/auth/v1beta1/accounts/secret1glew89c3jwk0a5n7kns68ek6lmzcjk6g9dpzmx? failed, reason: read ECONNRESET
    at ScrtAgent.upload (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@fadroma+scrt@10.1.0_@fadroma+agent@1.0.1_secretjs@1.9.3/node_modules/@fadroma/scrt/scrt-chain.ts:322:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FSUploader.upload (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@fadroma+agent@1.0.1/node_modules/@fadroma/agent/agent-services.ts:89:24)
    at async FSUploader.uploadMany (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@fadroma+agent@1.0.1/node_modules/@fadroma/agent/agent-services.ts:106:34)
    at async Deployment.deploy (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@fadroma+agent@1.0.1/node_modules/@fadroma/agent/agent-deploy.ts:112:13)
    at async Project.deploy (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@hackbg+fadroma@1.1.0_@hackbg+ganesha@4.2.0/node_modules/@hackbg/fadroma/fadroma.ts:196:13)
    at async Step.call (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@hackbg+cmds@3.0.0/node_modules/@hackbg/cmds/cmds-step.ts:26:28)
    at async Command.run (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@hackbg+cmds@3.0.0/node_modules/@hackbg/cmds/cmds-command.ts:36:26)
    at async CwStorageBenchmarksProject.run (file:///home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/@hackbg+cmds@3.0.0/node_modules/@hackbg/cmds/cmds.ts:133:20) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1
```

The devnet container is apparently up and healthy:

```log
~/lab/blockchain/cosmos/cw-storage-benchmarks 😿 docker ps 
CONTAINER ID   IMAGE                                           COMMAND                  CREATED              STATUS                        PORTS                                       NAMES
2cf1ac86e425   ghcr.io/hackbg/fadroma-devnet-scrt-1.9:master   "/usr/bin/node /devn…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:1317->1317/tcp, :::1317->1317/tcp   fadroma-devnet
🟢
```

The local state is present and looks fine:

`cat state/fadroma-devnet/devnet.json`:

```json
{
  "chainId": "fadroma-devnet",
  "containerId": "2cf1ac86e425468b96060c07dd82b3f10e04c9d08f0b678c95ca0de4482319f2",
  "port": 1317,
  "imageTag": "ghcr.io/hackbg/fadroma-devnet-scrt-1.9:master"
}
```

There are no error/failure logs found in the docker container itself when inspected with (docker logs)

**Comment by egasimus** [comment] 2023-08-18 11:14
This may be caused by `local network sharing` being disabled in Mullvad VPN. Mullvad users should try enabling that option as documented [here](https://github.com/hackbg/fadroma/blob/master/TROUBLESHOOTING.md#econnreset).

**Comment by mradkov** [comment] 2023-08-18 13:53
> This may be caused by `local network sharing` being disabled in Mullvad VPN. Mullvad users should try enabling that option as documented [here](https://github.com/hackbg/fadroma/blob/master/TROUBLESHOOTING.md#econnreset).

Tried enabling this, but still getting error. This time its different one tho.

## First run:

```log
~/lab/blockchain/cosmos/cw-storage-benchmarks 🌙 pnpm devnet deploy

> cw-storage-benchmarks@0.1.0 devnet /home/anon/lab/blockchain/cosmos/cw-storage-benchmarks
> FADROMA_PROJECT=./ops.ts FADROMA_CHAIN=ScrtDevnet fadroma "deploy"

@hackbg/fadroma 1.1.0
/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/ops.ts
Enabling TypeScript support...
(node:24867) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeScript support enabled.

 INFO  cw-storage-benchmarks at /home/anon/lab/blockchain/cosmos/cw-storage-benchmarks
 INFO  cw-storage-benchmarks on fadroma-devnet
 INFO  cw-storage-benchmarks deployment: 20230818_135144 (CwStorageBenchmarks)
  LOG  20230818_135144 2 contract(s) are not deployed
  LOG  CwStorageBenchmarks: 20230818_135144 making sure all 2 contract(s) are built
  LOG  build fadroma-bench found at wasm/fadroma-bench@HEAD.wasm
  LOG  build toolkit-bench found at wasm/toolkit-bench@HEAD.wasm
  LOG  CwStorageBenchmarks: 20230818_135144 making sure 2 contract(s) are uploaded
  LOG  upload (node:fs) found code id 1 at state/fadroma-devnet/upload/54014464c190a0f130db20ec814eaf22b7592b08f26af157350b8c07a036274d.json
  LOG  upload (node:fs) found cached code id 1 for code hash 54014464c190a0f130db20ec814eaf22b7592b08f26af157350b8c07a036274d
  LOG  upload (node:fs) found code id 2 at state/fadroma-devnet/upload/130a1e21213bcc810bcc443a518d1e649a9a25e2eb6a662297062406542df218.json
  LOG  upload (node:fs) found cached code id 2 for code hash 130a1e21213bcc810bcc443a518d1e649a9a25e2eb6a662297062406542df218
  LOG  20230818_135144 instantiating 2 contract(s)
  LOG  fadroma-bench init: 20230818_135144/fadroma-bench from code id 1 (fadroma-bench @ HEAD)
  LOG  fadroma-devnet @ localhost:1317 starting container d661641e
  LOG  docker container d661641e trailing logs, waiting for: Validating proposal
  LOG  docker container d661641e ~/.secretd/config/genesis.json missing -> performing genesis
  LOG  docker container d661641e Ensuring a clean slate...
  LOG  docker container d661641e Establishing initial config...
  LOG  docker container d661641e Adding genesis accounts...
  LOG  docker container d661641e Creating genesis transaction...
  LOG  docker container d661641e Genesis transaction written to "/root/.secretd/config/gentx/gentx-115aa0a629f5d70dd1d464bc7e42799e00f4edae.json"
  LOG  docker container d661641e Bootstrapping chain...
  LOG  docker container d661641e Sprinkling holy water...
  LOG  docker container d661641e Configuring the node to support lcp (CORS proxy)...
  LOG  docker container d661641e Spawning lcp (CORS proxy)...
  LOG  docker container d661641e Launching the node...
  LOG  docker container d661641e $ source /opt/sgxsdk/environment && RUST_BACKTRACE=1 secretd start --bootstrap --rpc.laddr tcp://0.0.0.0:26657 --grpc.address 0.0.0.0:9090 --grpc-web.address 0.0.0.0:9091
  LOG  docker container d661641e Validating proposal  1 with random:  bf9bae01aa5708436c74afbb8b5ed0a5844651161d6610cdcf88f26aeab54b526e4d1f04157ea9234c6bfa6dd0b72a34 proof:  b7fb60c43ff4f8ec2ef6c5f6a73bbf0c74661931741c2fd0527d994a204b67fc hash:  e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  LOG  docker found expected message: Validating proposal
  LOG  docker throwing 7 seconds away...
DEBUG  @hackbg/port: localhost:1317 Connecting...
 INFO  @hackbg/port: localhost:1317 Connected
  LOG  secret12y30cy89y7g3v06evh8rtrvs9nacefs8x65dh8 @ fadroma-devnet authenticated
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1

```

## Second attempt:

```log
~/lab/blockchain/cosmos/cw-storage-benchmarks 🌙 pnpm devnet deploy

> cw-storage-benchmarks@0.1.0 devnet /home/anon/lab/blockchain/cosmos/cw-storage-benchmarks
> FADROMA_PROJECT=./ops.ts FADROMA_CHAIN=ScrtDevnet fadroma "deploy"

@hackbg/fadroma 1.1.0
/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/ops.ts
Enabling TypeScript support...
(node:26276) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeScript support enabled.

 INFO  cw-storage-benchmarks at /home/anon/lab/blockchain/cosmos/cw-storage-benchmarks
 INFO  cw-storage-benchmarks on fadroma-devnet
 INFO  cw-storage-benchmarks deployment: 20230818_135314 (CwStorageBenchmarks)
  LOG  20230818_135314 2 contract(s) are not deployed
  LOG  CwStorageBenchmarks: 20230818_135314 making sure all 2 contract(s) are built
  LOG  build fadroma-bench found at wasm/fadroma-bench@HEAD.wasm
  LOG  build toolkit-bench found at wasm/toolkit-bench@HEAD.wasm
  LOG  CwStorageBenchmarks: 20230818_135314 making sure 2 contract(s) are uploaded
  LOG  upload (node:fs) found code id 1 at state/fadroma-devnet/upload/54014464c190a0f130db20ec814eaf22b7592b08f26af157350b8c07a036274d.json
  LOG  upload (node:fs) found cached code id 1 for code hash 54014464c190a0f130db20ec814eaf22b7592b08f26af157350b8c07a036274d
  LOG  upload (node:fs) found code id 2 at state/fadroma-devnet/upload/130a1e21213bcc810bcc443a518d1e649a9a25e2eb6a662297062406542df218.json
  LOG  upload (node:fs) found cached code id 2 for code hash 130a1e21213bcc810bcc443a518d1e649a9a25e2eb6a662297062406542df218
  LOG  20230818_135314 instantiating 2 contract(s)
  LOG  fadroma-bench init: 20230818_135314/fadroma-bench from code id 1 (fadroma-bench @ HEAD)
  LOG  fadroma-devnet @ localhost:1317 starting container d661641e
/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:343
      var msg = new Error(
                ^

Error: (HTTP code 304) container already started -  
    at /home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:343:17
    at getCause (/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:373:7)
    at Modem.buildPayload (/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:342:5)
    at IncomingMessage.<anonymous> (/home/anon/lab/blockchain/cosmos/cw-storage-benchmarks/node_modules/.pnpm/docker-modem@3.0.8/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  reason: 'container already started',
  statusCode: 304,
  json: Buffer(0) [Uint8Array] []
}

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1



```

**Comment by egasimus** [comment] 2023-08-18 14:00
Thanks, looking into it.

**Comment by egasimus** [comment] 2023-08-20 06:33
@mradkov I released a partial fix - you can test by creating a project with `npx @hackbg/fadroma@1.3.0-rc.1 create`

**Comment by mradkov** [comment] 2023-08-20 07:26
Initialized a new project (`test-project`) with contract (`test-contract`). Then invoked `pnpm devnet deploy` and getting the following:

```log
~/lab/blockchain/cosmos/test-project 😹 pnpm devnet deploy

> test-project@0.1.0 devnet /home/anon/lab/blockchain/cosmos/test-project
> FADROMA_PROJECT=./ops.ts FADROMA_CHAIN=ScrtDevnet fadroma "deploy"

@hackbg/fadroma 1.1.0
/home/anon/lab/blockchain/cosmos/test-project/ops.ts
Enabling TypeScript support...
(node:741932) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeScript support enabled.

file:///home/anon/lab/blockchain/cosmos/test-project/api.ts:4
-contract;
^

ReferenceError: contract is not defined
    at file:///home/anon/lab/blockchain/cosmos/test-project/api.ts:4:1
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:428:15)

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1
```

I think this is again getting back to https://github.com/hackbg/fadroma/issues/176#issuecomment-1666489877

## Trying the no-digit, no-hyphen contract name (`test`) results in the following:

```log
~/lab/blockchain/cosmos/test 😹 pnpm devnet deploy

> test@0.1.0 devnet /home/anon/lab/blockchain/cosmos/test
> FADROMA_PROJECT=./ops.ts FADROMA_CHAIN=ScrtDevnet fadroma "deploy"

@hackbg/fadroma 1.1.0
/home/anon/lab/blockchain/cosmos/test/ops.ts
Enabling TypeScript support...
(node:743852) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeScript support enabled.

file:///home/anon/lab/blockchain/cosmos/test/api.ts:18
export class Test extends Client {

SyntaxError: Identifier 'Test' has already been declared
    at CustomizedModuleLoader.moduleStrategy (node:internal/modules/esm/translators:116:18)
    at CustomizedModuleLoader.moduleProvider (node:internal/modules/esm/loader:190:14)

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1
```

## Supposedly fine name `SmartContract` :man_shrugging: 


```log
/lab/blockchain/cosmos/project 😹 pnpm devnet deploy

> project@0.1.0 devnet /home/anon/lab/blockchain/cosmos/project
> FADROMA_PROJECT=./ops.ts FADROMA_CHAIN=ScrtDevnet fadroma "deploy"

@hackbg/fadroma 1.1.0
/home/anon/lab/blockchain/cosmos/project/ops.ts
Enabling TypeScript support...
(node:744491) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeScript support enabled.

/home/anon/lab/blockchain/cosmos/project/node_modules/.pnpm/@hackbg+cmds@3.0.0/node_modules/@hackbg/cmds/cmds-ts.cli.cjs:26
    commands.run(process.argv.slice(3))
             ^

TypeError: commands.run is not a function
    at /home/anon/lab/blockchain/cosmos/project/node_modules/.pnpm/@hackbg+cmds@3.0.0/node_modules/@hackbg/cmds/cmds-ts.cli.cjs:26:14

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
🔴 1
```

**Comment by egasimus** [comment] 2023-08-20 19:18
Yep yep, 1st one is #176, no point testing it here.

2nd one is new, I also caught it today :D It's because the project name can't be the same as the contract name. Also 176-ish, I'll address it in one of my next few commits.

The third one is as perplexing as the `ERR_UNHANDLED_REJECTION` from your previous comment. Not immediately obvious why it ends up like that, we might have to go over it on a call or something if it persists.

What stands out to me is this - why would it be reporting `@hackbg/fadroma 1.1.0` and not `1.3.0-rc.1`? :thinking:

**Comment by egasimus** [comment] 2023-09-04 14:47
Closing, continuing with remaining devnet onboarding issue at #201

**Closed as completed by egasimus** 2023-09-04 14:47 UTC
Labels: bug
